name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: install
        run: pnpm i

      - name: staticcheck
        run: pnpm staticcheck

      - name: build
        run: pnpm build

      - name: semver
        id: semver
        uses: akshens/semver-tag@v4
        with:
          version: ${{ github.ref_name }}

      - name: publish
        run: pnpm publish --access public --no-git-checks --tag ${{ steps.semver.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
